[theme]
base = "dark"
primaryColor = "#00d4aa"
backgroundColor = "#0f0f23"
secondaryBackgroundColor = "#1e1e2e"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false