[theme]
primaryColor = "#4285F4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#2D3748"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false